# Generated by Django 3.1.2 on 2020-11-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meslivres', '0002_auto_20201112_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='email_text',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='name_text',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='passwork_text',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='Name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='email',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='password',
            field=models.CharField(default='', max_length=30),
        ),
    ]
